apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: secretsyncer
build:
  artifacts:
    - image: secretsyncer
      docker:
        dockerfile: Dockerfile
        target: runner
  tagPolicy:
    sha256: {}
  local:
    push: true
    useBuildkit: true
    concurrency: 0
deploy:
  helm:
    releases:
      - name: secretsyncer
        namespace: truth
        chartPath: charts/secretsyncer
        artifactOverrides:
          image: secretsyncer
        valuesFiles:
          - "values-skaffold.yaml"
        imageStrategy:
          helm: {}
