remote_theme: pages-themes/cayman@v0.2.0
repository: iamsmartad/secretsyncer
title: secretsyncer
description: sync kubernetes secrets between namespaces and across clusters
show_downloads: false
plugins:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
